name: Update Spotilife IPA

on:
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours
  workflow_dispatch:        # allow manual run

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install telethon PyGithub

      - name: Run update script
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_CHANNEL: "SpotilifeIPAs"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update.py

      - name: Commit updated apps.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add apps.json
          git commit -m "Update apps.json" || echo "No changes"
          git push
